apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/*
build:
  local:
    push: false
  artifacts:
    - image: umeshbhat/views-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*/js'
            dest: .
    - image: umeshbhat/views-server
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/**/*.js'
            dest: .
